### ISSUE TITLE
`martin-cp` and `mbtiles meta-update` should set metadata like minzoom, maxzoom, ...

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1081]
* [x] `martin-cp` should set correct `minzoom` and `maxzoom` based on the zoom parameters on the new file
* [x] when copying to an existing file, `martin-cp` should update `minzoom` and `maxzoom` based on the user input, but should NOT shrink it (lower max and increase min) if the `tiles` table has those zooms, even if they are not being copied in the correct operation
* [x] When `martin-cp` runs, it should set `pbf` instead of `mvt` when writing mbtiles's `format` property. QGIS expects that.
* [x] `mbtiles meta-update` should set min/max zooms
* [ ] `mbtiles meta-update` should allow the same `--set-meta PROP=VALUE` pair as `martin-cp`, including being able to override auto-computed values.
* [ ] Implement `mbtiles meta-update --delete-meta PROP`  (naming?)
* [ ] Implement `martin-cp meta-update --delete-meta PROP`  (naming?)

**Comment by bdon** [comment]
how about setting `compression`? https://github.com/protomaps/go-pmtiles/pull/106

https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#future-directions

**Comment by nyurik** [comment]
@bdon `martin-cp` supports `--encoding`, similar to a browser, so you can set it to `--encoding gzip` to force gzip compression when generating tiles.  What metadata are you thinking about in this context?

**Comment by bdon** [comment]
store the encoding type in the `compression` key in the metadata JSON, otherwise for type `pbf` you don't know without inspecting the bytes (magic number)

**Comment by nyurik** [comment]
@bdon code https://github.com/maplibre/martin/blob/main/mbtiles/src/metadata.rs#L104 parses metadata table and tries to make sense of it. As part of that parsing, `json` field is only [considered](https://github.com/maplibre/martin/blob/main/mbtiles/src/metadata.rs#L134) for `vector_layers`, which gets assigned to the tilejson (if it has the expected structure).

Do you want `compression` as part of that `json` field inside metadata?  Doesn't make much sense imo to have a simple key-value pair stored inside json when we already have a metadata table.  `pbf` is needed because otherwise QGIS wouldn't even view the file.

**Comment by bdon** [comment]
You're right, `compression` as a row in the metadata table not JSON. Does QGIS assume the `pbf` is gzip-encoded?

**Comment by nyurik** [comment]
yes, seems that way https://github.com/qgis/QGIS/blob/master/src/core/vectortile/qgsmbtilesvectortiledataprovider.cpp#L195

**Comment by nyurik** [comment]
@bdon lets discuss this in a new ticket - please create one, and we can iron out exactly what and when gets set?

**Comment by nyurik** [comment]
Continuing compression value discussion in #1085
