### ISSUE TITLE
Add server-side raster tile rendering

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#978]
Martin needs to be able to render and serve MVT tiles as rasters (JPG and/or PNG).

### TODO
* [x] https://github.com/maplibre/maplibre-native/issues/1057
  * [x] https://github.com/maplibre/maplibre-native/pull/3181
* [x] decide on URL endpoint changes
* [ ] decide on yaml configuration schema

**Comment by sharkAndshark** [comment]
I remember there is  a [maplibre-rs](https://github.com/maplibre/maplibre-rs), is it avaliable? I know little about it.   
And defintely `maplibre-native` is more mature, jsut for curious,

**Comment by nyurik** [comment]
maplibre-rs does not have most of the needed features, it can only show rudimentary no-font stuff

**Comment by GeorgeBarlow** [comment]
Is this still being actively looked into? I was looking for a good solution to use maplibre with rust but the current maplibre-rs repo seems as if it is still in the 'proof of concept' stage.

**Comment by nyurik** [comment]
Yeah, maplibre-rs is a POC.  The much more likely scenario is for https://github.com/maplibre/maplibre-native/issues/1057 to be implemented (@lseelenbinder was looking into it too)

**Comment by hkalbasi** [comment]
Would you accept a PR that includes (a narrow, only for this crate needs) binding for maplibre-native in this repo? We can always replace it with the proper bindings when it becomes created.

**Comment by nyurik** [comment]
Definitly!!!

**Comment by lucawen** [comment]
I created a mvp using actix and plain image lib to render raster based on OSG WMS specification. There is any reason to use maplibre instead ? Because i can just start to implement it in the martin instead of creating a new one

**Comment by CommanderStorm** [comment]
googling did not turn up good results. What is "plain image lib"?
How does this rendering work?

**Comment by lucawen** [comment]
> googling did not turn up good results. What is "plain image lib"? How does this rendering work?

Using mainly the geo, wkb and image lib. Of course, if we need to do more complex things, maybe we need more effort to create the features manually, instead of already having it from the mablibre. 
I have just created a repo of my POC. You can check it here. https://github.com/lucawen/geotiger/blob/main/src/services/wms_service.rs

EDIT: I did not implement any of the OSM specifications. Just a test to see the map rendering a layer.

**Comment by CommanderStorm** [comment]
https://github.com/lucawen/geotiger/blob/11cb1a92ee8fcf448359d8abdb3554c47d275774/src/services/wms_service.rs#L195-L220

Sorry, I don't think that this rendering can meet our quality bar.
We would like fullly styled maps, not just debug reprentations.
I would not like to maintain a tile renderer, a tile server has enough engineering-space.

That being said, there are some ideas in said implementation which might be advantageous for some of our tile sources like the second-layer cache (postgres, sometimes pmtiles, not mbtiles).

I think that fixing the rust wrapper for MLN is the simplest approach to get fully featured server side raster tile rendering.

**Comment by lucawen** [comment]
@CommanderStorm There is definitely no quality in this implementation, it's just a POC to see what it would be like in rust. But it makes sense not to want to maintain the render and the server. 

I will probably use my POC until martin server render becomes available. Do you have any expectations for when this will happen?

**Comment by CommanderStorm** [comment]
Well the biggest blocker on that front is improving https://github.com/maplibre/maplibre-native-rs

These are the open issues with are blocking [stabilisation of the  `unstable-rendering` feeature](https://maplibre.org/martin/sources-styles.html#server-side-raster-tile-rendering)
- [x] ~~logging which is not hooked up~~
- [x] ~~(can likely be defered) reducing the number and nastyness of dependencys https://github.com/maplibre/maplibre-native/issues/3483~~
- [ ] weird treading issues which I have not invested time in debugging
  - currently single-threaded, meaning tileserver-gl-js levels of performance.
  - See the following WHY this is single-threaded https://github.com/maplibre/maplibre-native-rs/pull/83
- [ ] (not a blocker) not integrated with the caching subsystem

All of this is not whichcraft, it just needs a bit of time which I currently have invested into other areas

**Comment by CommanderStorm** [comment]
We now stabilised this.
Performance still needs to be improved and there a re a few features left unimplmented, but lets discuss the gaps in the other issues
